const ideas = [
{ title: "Idea #1: Noche de películas favoritas", description: "Elijan películas que les traigan recuerdos, preparen algo rico y apaguen los celulares." },
{ title: "Idea #2: Paseo sin destino", description: "Salgan sin plan, decidan en el momento hacia dónde ir y qué hacer." },
{ title: "Idea #3: Escribirse cartas para el futuro", description: "Escriban lo que sienten hoy y acuerden leerlas dentro de un año." },
{ title: "Idea #4: Picnic al atardecer", description: "Busquen un lugar lindo, lleven algo para comer y vean caer el sol juntos." },
{ title: "Idea #5: Crear su playlist", description: "Armen una lista de canciones que represente su historia." },
{ title: "Idea #6: Día sin redes", description: "Guarden los teléfonos y pasen el día conectados entre ustedes." },
{ title: "Idea #7: Noche de juegos de mesa", description: "Elijan juegos y armen un pequeño torneo." },
{ title: "Idea #8: Desayuno sorpresa", description: "Uno sorprende al otro con desayuno en la cama." },
{ title: "Idea #9: Caminata profunda", description: "Salgan a caminar y hablen de sueños y planes." },
{ title: "Idea #10: Ver fotos viejas", description: "Recuerden cómo empezó todo." },
{ title: "Idea #11: Lista de sueños juntos", description: "Anoten metas y planes que quieran cumplir." },
{ title: "Idea #12: Cocinar algo nuevo", description: "Elijan una receta que nunca hicieron." },
{ title: "Idea #13: Noche temática", description: "Elijan un país o época y armen la noche con ese tema." },
{ title: "Idea #14: Cartel de metas", description: "Hagan un collage con objetivos del año." },
{ title: "Idea #15: Maratón de serie", description: "Miren varios capítulos seguidos." },
{ title: "Idea #16: Paseo en bici", description: "Recorran la ciudad o un parque." },
{ title: "Idea #17: Día de fotos", description: "Salgan a sacar fotos creativas juntos." },
{ title: "Idea #18: Escribirse cualidades", description: "Díganse lo que más admiran del otro." },
{ title: "Idea #19: Helado nocturno", description: "Salir de noche solo por algo dulce." },
{ title: "Idea #20: Mirar las estrellas", description: "Hablar de su futuro mirando el cielo." },
{ title: "Idea #21: Frasco de recuerdos", description: "Escriban momentos lindos y guárdenlos." },
{ title: "Idea #22: Competencia de cocina", description: "Cada uno cocina algo y se votan." },
{ title: "Idea #23: Preguntas profundas", description: "Prepárense preguntas para conocerse más." },
{ title: "Idea #24: Cápsula del tiempo", description: "Guarden objetos para abrir en el futuro." },
{ title: "Idea #25: Ver el amanecer", description: "Despertarse temprano para verlo juntos." },
{ title: "Idea #26: Diario de pareja", description: "Anoten momentos importantes." },
{ title: "Idea #27: Tarde de manualidades", description: "Crear algo con las manos." },
{ title: "Idea #28: Caminata larga", description: "Caminar sin apuro." },
{ title: "Idea #29: Día sin reloj", description: "No mirar la hora en todo el día." },
{ title: "Idea #30: Planear un viaje", description: "Soñar con un viaje futuro." },
{ title: "Idea #31: Karaoke en casa", description: "Canten sus canciones favoritas." },
{ title: "Idea #32: Ver documental", description: "Aprender algo nuevo juntos." },
{ title: "Idea #33: Carta a su yo futuro", description: "Escriban cómo se ven en 5 años." },
{ title: "Idea #34: Día sin gastar", description: "Inventen planes gratis." },
{ title: "Idea #35: Explorar barrio nuevo", description: "Conocer una zona desconocida." },
{ title: "Idea #36: Cocinar para otros", description: "Preparar comida para alguien querido." },
{ title: "Idea #37: Película sorpresa", description: "Ver una peli que ninguno conoce." },
{ title: "Idea #38: Escribir un cuento", description: "Inventar una historia entre los dos." },
{ title: "Idea #39: Juegos retro", description: "Jugar videojuegos clásicos." },
{ title: "Idea #40: Fotos divertidas", description: "Sesión de fotos graciosas." },
{ title: "Idea #41: Bucket list de pareja", description: "Lista de cosas por hacer juntos." },
{ title: "Idea #42: Atardecer desde lo alto", description: "Buscar un punto con buena vista." },
{ title: "Idea #43: Regalos hechos a mano", description: "Crear algo personal para el otro." },
{ title: "Idea #44: Viaje en colectivo al azar", description: "Subirse y ver a dónde llegan." },
{ title: "Idea #45: Maratón de risas", description: "Ver videos graciosos sin parar." },
{ title: "Idea #46: Aprender una habilidad", description: "Elegir algo nuevo para practicar." },
{ title: "Idea #47: Rompecabezas", description: "Armar uno grande juntos." },
{ title: "Idea #48: Metas personales", description: "Compartir objetivos y apoyarse." },
{ title: "Idea #49: Tarde de dibujo", description: "Dibujarse mutuamente." },
{ title: "Idea #50: Postre casero", description: "Preparar algo dulce." },
{ title: "Idea #51: Película clásica", description: "Ver una película antigua." },
{ title: "Idea #52: Playlist para viajar", description: "Armar música para futuros viajes." },
{ title: "Idea #53: Caminata nocturna", description: "Recorrer calles tranquilas." },
{ title: "Idea #54: Día sin quejas", description: "Intentar no quejarse de nada." },
{ title: "Idea #55: Evento cultural", description: "Ir a un show u obra." },
{ title: "Idea #56: Cocina internacional", description: "Elegir un país y cocinar su comida." },
{ title: "Idea #57: Soñar destinos", description: "Ver fotos de lugares del mundo." },
{ title: "Idea #58: Lo mejor del año", description: "Recordar momentos importantes." },
{ title: "Idea #59: Juegos de cartas", description: "Pasar la tarde jugando." },
{ title: "Idea #60: Amanecer en la cama", description: "Ver salir el sol juntos." },
{ title: "Idea #61: Crear tradición", description: "Inventar una costumbre propia." },
{ title: "Idea #62: Limpieza con música", description: "Ordenar escuchando canciones." },
{ title: "Idea #63: Película extranjera", description: "Probar cine de otro país." },
{ title: "Idea #64: Cartas de agradecimiento", description: "Agradecer cosas de su relación." },
{ title: "Idea #65: Cocinar para familia", description: "Compartir comida con otros." },
{ title: "Idea #66: Salida improvisada", description: "Salir sin plan." },
{ title: "Idea #67: Nuevo atardecer", description: "Buscar un lugar distinto para verlo." },
{ title: "Idea #68: Caja de recuerdos", description: "Guardar objetos importantes." },
{ title: "Idea #69: Video de recuerdos", description: "Grabar momentos juntos." },
{ title: "Idea #70: Día de lectura", description: "Leer en silencio uno al lado del otro." },
{ title: "Idea #71: Librería juntos", description: "Elegir libros para leer." },
{ title: "Idea #72: Noche de historias", description: "Contarse anécdotas." },
{ title: "Idea #73: Aprender a bailar", description: "Practicar pasos de algún baile." },
{ title: "Idea #74: Calendario de sueños", description: "Anotar planes futuros." },
{ title: "Idea #75: Tarde en la plaza", description: "Pasar horas charlando al aire libre." },
{ title: "Idea #76: Juego de preguntas", description: "Inventar preguntas divertidas." },
{ title: "Idea #77: Cocinar desayuno juntos", description: "Preparar el desayuno entre los dos." },
{ title: "Idea #78: Mirar el cielo", description: "Buscar formas en las nubes." },
{ title: "Idea #79: Mapa de recuerdos", description: "Marcar lugares importantes." },
{ title: "Idea #80: Día creativo", description: "Pintar, escribir o crear algo." },
{ title: "Idea #81: Ver fotos de infancia", description: "Compartir recuerdos de chicos." },
{ title: "Idea #82: Juegos al aire libre", description: "Frisbee, pelota, lo que sea." },
{ title: "Idea #83: Escribir metas del mes", description: "Organizar próximos objetivos." },
{ title: "Idea #84: Playlist del momento", description: "Canciones que los representen hoy." },
{ title: "Idea #85: Salida con mate", description: "Caminar y charlar con mate." },
{ title: "Idea #86: Mini picnic en casa", description: "Comer en el piso como picnic." },
{ title: "Idea #87: Desafío de dibujo", description: "Dibujar cosas al azar." },
{ title: "Idea #88: Ver el atardecer urbano", description: "Desde la ciudad." },
{ title: "Idea #89: Noche de acertijos", description: "Resolver enigmas juntos." },
{ title: "Idea #90: Caminata silenciosa", description: "Caminar sin hablar y observar." },
{ title: "Idea #91: Hacer una lista de recuerdos", description: "Escribir momentos importantes." },
{ title: "Idea #92: Día de improvisación", description: "Improvisar actividades." },
{ title: "Idea #93: Juego de roles creativos", description: "Inventar personajes." },
{ title: "Idea #94: Paseo fotográfico", description: "Sacar fotos artísticas." },
{ title: "Idea #95: Visitar un museo", description: "Aprender y recorrer." },
{ title: "Idea #96: Hacer un podcast casero", description: "Grabar charlas divertidas." },
{ title: "Idea #97: Tarde de puzzles", description: "Resolver rompecabezas pequeños." },
{ title: "Idea #98: Día de no quejarse", description: "Intentar mantener actitud positiva." },
{ title: "Idea #99: Mirar lluvia", description: "Observarla desde una ventana." },
{ title: "Idea #100: Crear su logo", description: "Diseñar un símbolo de la pareja." },
{ title: "Idea #101: Escribir una canción", description: "Inventar letra y melodía." },
{ title: "Idea #102: Maratón de cortos", description: "Ver cortometrajes." },
{ title: "Idea #103: Planear fin de semana", description: "Organizar próxima salida." },
{ title: "Idea #104: Aprender palabras nuevas", description: "En otro idioma." },
{ title: "Idea #105: Salida con cámara", description: "Tomar fotos por la ciudad." },
{ title: "Idea #106: Mirar una serie vieja", description: "Revivir clásicos." },
{ title: "Idea #107: Día de recuerdos", description: "Hablar del pasado." },
{ title: "Idea #108: Crear un mural", description: "Dibujar algo grande juntos." },
{ title: "Idea #109: Ver animales", description: "Ir a una plaza o reserva." },
{ title: "Idea #110: Escribir metas del año", description: "Proyectar el futuro." },
{ title: "Idea #111: Tarde sin pantallas", description: "Jugar, hablar y crear." },
{ title: "Idea #112: Paseo en tren", description: "Viajar y observar." },
{ title: "Idea #113: Noche de acertijos", description: "Resolver misterios." },
{ title: "Idea #114: Crear su calendario", description: "Marcar fechas importantes." },
{ title: "Idea #115: Escuchar álbum completo", description: "Disfrutar música de principio a fin." },
{ title: "Idea #116: Día de postres", description: "Probar cosas dulces." },
{ title: "Idea #117: Salida sorpresa", description: "Uno organiza sin decir nada." },
{ title: "Idea #118: Caminar bajo la lluvia", description: "Si el clima acompaña." },
{ title: "Idea #119: Hacer un collage", description: "Con revistas o fotos." },
{ title: "Idea #120: Escribir agradecimientos", description: "Decirse lo que valoran." },
{ title: "Idea #121: Armar una playlist de recuerdos", description: "Cada uno agrega canciones que le recuerden momentos juntos y después la escuchan entera mientras charlan de por qué eligieron cada tema." },
{ title: "Idea #122: Escribirse cartas para leer dentro de un año", description: "Se escriben una carta cada uno y la guardan para abrirla en la misma fecha del año siguiente." },
{ title: "Idea #123: Salida sorpresa sin decir el destino", description: "Uno organiza todo y el otro se deja llevar sin saber a dónde van ni qué van a hacer." },
{ title: "Idea #124: Día sin pantallas juntos", description: "Apagan los celulares por varias horas y se enfocan solo en compartir, charlar y disfrutar el momento." },
{ title: "Idea #125: Cocinar una comida de otro país", description: "Eligen un país al azar y cocinan una receta típica escuchando música de ese lugar." },
{ title: "Idea #126: Escribir una lista de metas en pareja", description: "Definen metas a corto, mediano y largo plazo para ustedes como pareja." },
{ title: "Idea #127: Recrear su primera cita", description: "Intentan repetir lo más fiel posible cómo fue su primera salida juntos." },
{ title: "Idea #128: Hacer un frasco de frases lindas", description: "Escriben mensajes positivos y románticos para leer cuando uno esté bajón." },
{ title: "Idea #129: Maratón de pelis con temática elegida", description: "Eligen una temática (romance, terror, aventura) y ven varias películas seguidas." },
{ title: "Idea #130: Crear un logo de la pareja", description: "Diseñan un símbolo que represente su relación." },
{ title: "Idea #131: Ir a ver el amanecer juntos", description: "Se levantan temprano y ven salir el sol en un lugar lindo." },
{ title: "Idea #132: Picnic improvisado", description: "Compran cosas simples y se van a una plaza o parque sin mucha planificación." },
{ title: "Idea #133: Noche de juegos de mesa", description: "Eligen varios juegos y hacen mini torneos entre ustedes." },
{ title: "Idea #134: Escribir una historia sobre ustedes", description: "Inventan una historia ficticia donde ustedes son los protagonistas." },
{ title: "Idea #135: Hacer una cápsula del tiempo", description: "Guardan objetos y cartas para abrir en el futuro." },
{ title: "Idea #136: Aprender algo nuevo juntos", description: "Puede ser bailar, cocinar algo nuevo, un idioma, lo que quieran." },
{ title: "Idea #137: Crear un álbum digital", description: "Ordenan fotos y recuerdos en un álbum online." },
{ title: "Idea #138: Competencia de cocina", description: "Cada uno cocina algo y se califican entre ustedes." },
{ title: "Idea #139: Día de mimos", description: "Se dedican todo el día a cuidarse y mimarse mutuamente." },
{ title: "Idea #140: Ver las estrellas", description: "Buscan un lugar oscuro y miran el cielo juntos." },
{ title: "Idea #141: Hacer una lista de sueños locos", description: "Anotan todas las cosas que sueñan hacer juntos, incluso las más imposibles." },
{ title: "Idea #142: Grabar un video mensaje al futuro", description: "Se graban hablando de cómo se sienten hoy." },
{ title: "Idea #143: Día de spa casero", description: "Arman una tarde de relax con música y cuidado personal." },
{ title: "Idea #144: Escribir promesas de pareja", description: "Cada uno escribe promesas para el otro." },
{ title: "Idea #145: Noche temática de otro país", description: "Comida, música y vestimenta inspirada en un país." },
{ title: "Idea #146: Hacer un mapa de viajes soñados", description: "Marcan todos los lugares que quieren visitar juntos." },
{ title: "Idea #147: Leer un libro juntos", description: "Eligen un libro y lo leen al mismo tiempo." },
{ title: "Idea #148: Crear una rutina de pareja", description: "Definen pequeños hábitos diarios para fortalecer la relación." },
{ title: "Idea #149: Planear una mini escapada", description: "Organizan un viaje corto para más adelante." },
{ title: "Idea #150: Escribir 50 cosas que aman del otro", description: "Se intercambian listas con razones por las que se quieren." },
{ title: "Idea #151: Noche de preguntas profundas", description: "Se hacen preguntas importantes para conocerse más." },
{ title: "Idea #152: Salir a caminar sin rumbo", description: "Caminan sin destino fijo y ven a dónde llegan." },
{ title: "Idea #153: Crear un diario de pareja", description: "Anotan experiencias y pensamientos compartidos." },
{ title: "Idea #154: Hacer una playlist para viajes", description: "Arman música ideal para viajar juntos." },
{ title: "Idea #155: Aprender a cocinar un postre", description: "Eligen un postre y lo hacen entre los dos." },
{ title: "Idea #156: Ver fotos viejas juntos", description: "Reviven recuerdos mirando fotos." },
{ title: "Idea #157: Armar una caja de recuerdos", description: "Guardan objetos importantes de la relación." },
{ title: "Idea #158: Escribir una canción para ustedes", description: "Inventan una letra que represente su historia." },
{ title: "Idea #159: Desayuno sorpresa", description: "Uno prepara un desayuno especial para el otro." },
{ title: "Idea #160: Día sin quejas", description: "Intentan pasar todo el día sin quejarse de nada." },
{ title: "Idea #161: Dibujarse mutuamente", description: "Cada uno hace un dibujo del otro, sin importar el resultado." },
{ title: "Idea #162: Salida de fotos", description: "Van a sacar fotos creativas por la ciudad." },
{ title: "Idea #163: Hacer un reto de 30 días juntos", description: "Se proponen un desafío para un mes." },
{ title: "Idea #164: Escribir un contrato de pareja divertido", description: "Redactan reglas graciosas para la relación." },
{ title: "Idea #165: Crear su propio juego", description: "Inventan un juego solo para ustedes." },
{ title: "Idea #166: Mirar un atardecer juntos", description: "Buscar un lugar especial para ver caer el sol." },
{ title: "Idea #167: Intercambiar playlists secretas", description: "Cada uno arma una playlist para el otro." },
{ title: "Idea #168: Hacer una lista de metas personales", description: "Se ayudan a definir objetivos individuales." },
{ title: "Idea #169: Día de recuerdos", description: "Hablan de todo lo que vivieron juntos hasta hoy." },
{ title: "Idea #170: Crear un mural de sueños", description: "Hacen un collage con todo lo que quieren lograr." },
{ title: "Idea #171: Maratón de su serie favorita", description: "Ven varios capítulos seguidos sin interrupciones." },
{ title: "Idea #172: Escribir una carta de agradecimiento", description: "Se agradecen por todo lo que comparten." },
{ title: "Idea #173: Hacer una caminata larga", description: "Salen a caminar durante horas charlando." },
{ title: "Idea #174: Crear un ritual de pareja", description: "Inventan una costumbre solo de ustedes." },
{ title: "Idea #175: Jugar a las preguntas incómodas", description: "Se hacen preguntas difíciles de responder." },
{ title: "Idea #176: Hacer una sesión de fotos casera", description: "Se sacan fotos lindas con el celular." },
{ title: "Idea #177: Noche de anécdotas", description: "Se cuentan historias de su vida." },
{ title: "Idea #178: Crear un calendario de citas", description: "Planean fechas especiales durante el año." },
{ title: "Idea #179: Hacer una playlist para dormir", description: "Arman música para relajarse juntos." },
{ title: "Idea #180: Mirar el cielo desde una terraza", description: "Suben a un lugar alto y observan la noche." },
{ title: "Idea #181: Hacer una lista de agradecimientos", description: "Escriben cosas por las que están agradecidos." },
{ title: "Idea #182: Armar una tarde de manualidades", description: "Crean algo con sus manos." },
{ title: "Idea #183: Leer poesía juntos", description: "Comparten poemas y reflexiones." },
{ title: "Idea #184: Hacer una noche de improvisación", description: "Inventan escenas y situaciones." },
{ title: "Idea #185: Armar una cápsula de canciones", description: "Guardan temas que los representen este año." },
{ title: "Idea #186: Hacer una caminata nocturna", description: "Salir a caminar de noche charlando." },
{ title: "Idea #187: Día de gratitud mutua", description: "Se dicen cosas que valoran del otro." },
{ title: "Idea #188: Crear un mural de fotos", description: "Imprimen fotos y las pegan en la pared." },
{ title: "Idea #189: Aprender un truco juntos", description: "Puede ser magia, cartas, lo que quieran." },
{ title: "Idea #190: Hacer una carta para el futuro", description: "Se escriben una carta para leer más adelante." },
{ title: "Idea #191: Cocinar una cena romántica", description: "Preparan una comida especial entre los dos." },
{ title: "Idea #192: Hacer una noche de juegos retro", description: "Juegan juegos viejos o clásicos." },
{ title: "Idea #193: Crear un video de recuerdos", description: "Editan un video con momentos juntos." },
{ title: "Idea #194: Armar un frasco de sueños", description: "Escriben sueños y los guardan." },
{ title: "Idea #195: Noche de música en vivo", description: "Escuchan conciertos o tocan música." },
{ title: "Idea #196: Planear una tradición anual", description: "Inventan una costumbre para cada año." },
{ title: "Idea #197: Salida en bicicleta", description: "Van a andar en bici juntos." },
{ title: "Idea #198: Día de reflexión", description: "Hablan sobre su crecimiento como pareja." },
{ title: "Idea #199: Crear un código secreto", description: "Inventan palabras solo de ustedes." },
{ title: "Idea #200: Ver fotos del futuro", description: "Imaginar cómo serán dentro de 10 años." },
{ title: "Idea #201: Hacer una lista de lugares favoritos", description: "Anoten todos los lugares donde ya fueron juntos y cuáles quieren repetir." },
{ title: "Idea #202: Crear un reto semanal de pareja", description: "Cada semana se proponen un pequeño desafío para cumplir juntos." },
{ title: "Idea #203: Tarde de helado artesanal", description: "Salen a probar sabores nuevos y eligen su favorito." },
{ title: "Idea #204: Jugar a planear su casa ideal", description: "Dibujan cómo sería su casa soñada." },
{ title: "Idea #205: Maratón de videos graciosos", description: "Ríanse juntos viendo videos hasta que les duela la panza." },
{ title: "Idea #206: Escribir una carta sin decir 'te amo'", description: "Expresarse con otras palabras creativas." },
{ title: "Idea #207: Armar un tablero de metas", description: "Pegan imágenes y palabras de lo que quieren lograr." },
{ title: "Idea #208: Cocinar con ingredientes al azar", description: "Eligen ingredientes sin planear y crean una comida." },
{ title: "Idea #209: Día de fotos espontáneas", description: "Sacarse fotos durante todo el día sin posar." },
{ title: "Idea #210: Mirar el amanecer desde el auto", description: "Estacionan en un lugar lindo y esperan que salga el sol." },

{ title: "Idea #211: Intercambiar diarios por un día", description: "Leer lo que el otro escribe sobre su día." },
{ title: "Idea #212: Armar una tarde de picnic urbano", description: "Comer algo rico sentados en una plaza." },
{ title: "Idea #213: Escribir una lista de primeras veces", description: "Anotar todas las cosas que hicieron por primera vez juntos." },
{ title: "Idea #214: Noche de preguntas locas", description: "Se hacen preguntas absurdas y divertidas." },
{ title: "Idea #215: Hacer una maratón de documentales", description: "Elijan temas que les interesen." },
{ title: "Idea #216: Planear un viaje imposible", description: "Imaginar un viaje sin límite de presupuesto." },
{ title: "Idea #217: Armar un collage de emociones", description: "Usan revistas o dibujos para representar cómo se sienten juntos." },
{ title: "Idea #218: Noche de karaoke", description: "Cantar sus canciones favoritas." },
{ title: "Idea #219: Día de recuerdos felices", description: "Recordar solo momentos lindos de la relación." },
{ title: "Idea #220: Escribir una carta al presente", description: "Hablar de lo que sienten hoy." },

{ title: "Idea #221: Crear una tradición de aniversario", description: "Inventar algo que hagan cada año." },
{ title: "Idea #222: Caminata por un barrio nuevo", description: "Explorar una zona que no conocen." },
{ title: "Idea #223: Hacer una lista de logros juntos", description: "Todo lo que superaron como pareja." },
{ title: "Idea #224: Armar una noche de preguntas profundas 2", description: "Segunda ronda de preguntas más intensas." },
{ title: "Idea #225: Crear su propio calendario de eventos", description: "Marcar fechas importantes." },
{ title: "Idea #226: Tarde de dibujo libre", description: "Dibujar sin reglas." },
{ title: "Idea #227: Hacer una playlist para cada emoción", description: "Feliz, triste, motivado, etc." },
{ title: "Idea #228: Noche de improvisación teatral", description: "Inventar escenas divertidas." },
{ title: "Idea #229: Armar un proyecto juntos", description: "Algo que puedan construir con el tiempo." },
{ title: "Idea #230: Hacer una lista de promesas futuras", description: "Promesas que quieren cumplir." },

{ title: "Idea #231: Día de sorpresas pequeñas", description: "Hacerse mini sorpresas todo el día." },
{ title: "Idea #232: Crear un frasco de mensajes motivadores", description: "Para cuando uno esté bajón." },
{ title: "Idea #233: Noche de estrellas fugaces", description: "Salir a ver el cielo." },
{ title: "Idea #234: Escribir un cuento romántico", description: "Una historia inspirada en ustedes." },
{ title: "Idea #235: Aprender un juego nuevo", description: "De cartas, mesa o digital." },
{ title: "Idea #236: Salida sin destino", description: "Subirse al primer colectivo que pase." },
{ title: "Idea #237: Hacer un reto de fotos creativas", description: "Fotos raras y divertidas." },
{ title: "Idea #238: Crear un ritual nocturno", description: "Algo especial antes de dormir." },
{ title: "Idea #239: Mirar su película favorita otra vez", description: "Y comentar detalles nuevos." },
{ title: "Idea #240: Escribir cartas anónimas", description: "Decirse cosas sin decir quién escribe." },

{ title: "Idea #241: Día de caminata larga", description: "Caminar hasta cansarse y luego comer algo rico." },
{ title: "Idea #242: Armar un mini emprendimiento ficticio", description: "Imaginar un negocio juntos." },
{ title: "Idea #243: Hacer una lista de sueños cumplidos", description: "Todo lo que ya lograron." },
{ title: "Idea #244: Tarde de cocina saludable", description: "Preparar comidas sanas." },
{ title: "Idea #245: Noche de anécdotas graciosas", description: "Recordar momentos divertidos." },
{ title: "Idea #246: Armar una playlist para entrenar", description: "Canciones que motiven." },
{ title: "Idea #247: Hacer un mural de metas personales", description: "Cada uno con sus objetivos." },
{ title: "Idea #248: Crear una rutina de gratitud diaria", description: "Decirse algo bueno todos los días." },
{ title: "Idea #249: Día de silencio compartido", description: "Estar juntos sin hablar, solo acompañarse." },
{ title: "Idea #250: Escribir una carta para su yo del futuro", description: "Qué esperan de ustedes mismos." },

{ title: "Idea #251: Crear un ritual de despedida", description: "Algo que hagan cada vez que se separan." },
{ title: "Idea #252: Noche de películas antiguas", description: "Ver clásicos del cine." },
{ title: "Idea #253: Planear un año soñado", description: "Cómo quieren que sea su próximo año juntos." },
{ title: "Idea #254: Hacer una tarde de puzzles", description: "Armar rompecabezas juntos." },
{ title: "Idea #255: Crear una playlist para viajar en auto", description: "Canciones para la ruta." },
{ title: "Idea #256: Armar un libro de frases propias", description: "Escribir pensamientos y frases juntos." },
{ title: "Idea #257: Hacer un día sin reloj", description: "Vivir sin mirar la hora." },
{ title: "Idea #258: Noche de historias inventadas", description: "Contarse cuentos creados por ustedes." },
{ title: "Idea #259: Crear una cápsula de recuerdos del mes", description: "Guardar lo más importante del mes." },
{ title: "Idea #260: Hacer una lista de lugares donde quieren volver", description: "Todos los sitios que quieren repetir." },

{ title: "Idea #261: Armar un desafío mensual", description: "Un reto para todo el mes." },
{ title: "Idea #262: Tarde de arte abstracto", description: "Pintar sin reglas." },
{ title: "Idea #263: Noche de charlas profundas", description: "Hablar de la vida y el futuro." },
{ title: "Idea #264: Crear un plan de sueños compartidos", description: "Unir sus sueños en uno." },
{ title: "Idea #265: Hacer una lista de cosas que los hacen reír", description: "Anotar todo lo que les da gracia." },
{ title: "Idea #266: Caminata bajo la lluvia", description: "Salir aunque llueva." },
{ title: "Idea #267: Armar un día de fotos blanco y negro", description: "Sacar fotos solo en ese estilo." },
{ title: "Idea #268: Crear un ritual de inicio de semana", description: "Algo que hagan todos los lunes." },
{ title: "Idea #269: Noche de cuentos reales", description: "Contarse historias verdaderas de su vida." },
{ title: "Idea #270: Escribir una carta de agradecimiento mutua", description: "Decirse lo mucho que se valoran." },

{ title: "Idea #271: Hacer un recorrido por su historia", description: "Repasar cómo empezó todo." },
{ title: "Idea #272: Armar una playlist para cada estación", description: "Una por verano, otoño, invierno y primavera." },
{ title: "Idea #273: Crear una lista de metas imposibles", description: "Soñar sin límites." },
{ title: "Idea #274: Tarde de juegos de infancia", description: "Jugar como cuando eran chicos." },
{ title: "Idea #275: Planear una sorpresa para el otro", description: "Organizar algo sin que el otro sepa." },
{ title: "Idea #276: Día de preguntas sin filtro", description: "Preguntas honestas y profundas." },
{ title: "Idea #277: Crear un mural de recuerdos favoritos", description: "Pegar sus momentos más lindos." },
{ title: "Idea #278: Noche de cocina italiana", description: "Pasta, pizza y música italiana." },
{ title: "Idea #279: Escribir una lista de lo que aprendieron juntos", description: "Lecciones de la relación." },
{ title: "Idea #280: Crear una tradición mensual", description: "Algo especial para repetir cada mes." },
{ title: "Idea #281: Hacer una noche de películas malas", description: "Elegir pelis tan malas que sean divertidas y comentarlas todo el tiempo." },
{ title: "Idea #282: Crear una lista de cosas pendientes juntos", description: "Anotar todo lo que quieren hacer en el futuro cercano." },
{ title: "Idea #283: Salida de café al azar", description: "Entrar al primer café que vean caminando." },
{ title: "Idea #284: Día de desafíos divertidos", description: "Inventar pequeños retos para cumplir durante el día." },
{ title: "Idea #285: Armar una playlist solo con canciones que los representen", description: "Nada de relleno, solo temas importantes." },
{ title: "Idea #286: Escribir una carta sin decir nombres", description: "Describir al otro sin decir quién es." },
{ title: "Idea #287: Crear una lista de sueños para este año", description: "Metas específicas para los próximos meses." },
{ title: "Idea #288: Tarde de juegos de cartas", description: "Competencia amistosa con castigos graciosos." },
{ title: "Idea #289: Caminar escuchando la misma música", description: "Compartir auriculares y caminar juntos." },
{ title: "Idea #290: Noche de historias de miedo", description: "Contarse historias oscuras y misteriosas." },

{ title: "Idea #291: Escribir un manifiesto de pareja", description: "Definir qué tipo de relación quieren construir." },
{ title: "Idea #292: Tarde de limpieza juntos", description: "Ordenar escuchando música y charlando." },
{ title: "Idea #293: Crear un calendario de sueños", description: "Marcar cuándo quieren cumplir cada sueño." },
{ title: "Idea #294: Hacer una lista de cosas que los hacen únicos", description: "Qué los diferencia como pareja." },
{ title: "Idea #295: Noche de fotos ridículas", description: "Sacarse las fotos más graciosas posibles." },
{ title: "Idea #296: Salida sin gastar dinero", description: "Ver cuántas cosas pueden hacer sin gastar nada." },
{ title: "Idea #297: Escribir cartas que nunca van a enviar", description: "Expresar todo sin filtros." },
{ title: "Idea #298: Crear una playlist para cocinar", description: "Música perfecta para la cocina." },
{ title: "Idea #299: Día de elogios", description: "Decirse cosas lindas todo el día." },
{ title: "Idea #300: Hacer una lista de todo lo que aman del otro", description: "Sin repetir nada." },

{ title: "Idea #301: Crear un ritual de viernes", description: "Algo que hagan todos los viernes." },
{ title: "Idea #302: Noche de películas de su infancia", description: "Ver cosas que veían de chicos." },
{ title: "Idea #303: Escribir una carta al pasado", description: "Hablarle a su yo de antes." },
{ title: "Idea #304: Armar una tarde de desafíos creativos", description: "Dibujar, escribir, inventar cosas." },
{ title: "Idea #305: Salida nocturna improvisada", description: "Salir de noche sin planear nada." },
{ title: "Idea #306: Crear una lista de momentos favoritos", description: "Sus recuerdos más lindos." },
{ title: "Idea #307: Hacer una caminata larga en silencio", description: "Caminar sin hablar, solo acompañarse." },
{ title: "Idea #308: Noche de confesiones", description: "Decirse cosas que nunca dijeron." },
{ title: "Idea #309: Armar un frasco de deseos", description: "Escribir deseos y guardarlos." },
{ title: "Idea #310: Crear un calendario de aventuras", description: "Planear experiencias futuras." },

{ title: "Idea #311: Hacer una tarde de voluntariado", description: "Ayudar juntos en algo solidario." },
{ title: "Idea #312: Escribir una carta de despedida al año", description: "Reflexionar sobre todo lo vivido." },
{ title: "Idea #313: Crear un mapa de recuerdos", description: "Marcar dónde vivieron cada experiencia." },
{ title: "Idea #314: Noche de música lenta", description: "Escuchar música y relajarse juntos." },
{ title: "Idea #315: Hacer una lista de proyectos de vida", description: "Qué quieren construir juntos." },
{ title: "Idea #316: Salir a caminar sin rumbo de noche", description: "Explorar la ciudad juntos." },
{ title: "Idea #317: Crear una playlist de despedidas", description: "Para momentos de cambio." },
{ title: "Idea #318: Noche de arte y vino (o jugo)", description: "Pintar y charlar." },
{ title: "Idea #319: Armar una lista de cosas que quieren aprender juntos", description: "Habilidades y conocimientos." },
{ title: "Idea #320: Hacer un ritual de inicio de mes", description: "Algo simbólico para cada mes." },

{ title: "Idea #321: Crear una tarde sin redes sociales", description: "Desconectarse del mundo digital juntos." },
{ title: "Idea #322: Escribir una carta al futuro de la pareja", description: "Cómo imaginan su relación." },
{ title: "Idea #323: Armar una playlist para días tristes", description: "Canciones que consuelen." },
{ title: "Idea #324: Salida a ver el atardecer", description: "Buscar un buen lugar y mirar el cielo." },
{ title: "Idea #325: Noche de preguntas que nunca hicieron", description: "Conocerse más." },
{ title: "Idea #326: Crear una lista de tradiciones propias", description: "Costumbres solo de ustedes." },
{ title: "Idea #327: Hacer una caminata con fotos", description: "Documentar el paseo con fotos." },
{ title: "Idea #328: Escribir una carta a sus sueños", description: "Hablarle a lo que quieren lograr." },
{ title: "Idea #329: Armar una playlist para el futuro", description: "Música que represente lo que viene." },
{ title: "Idea #330: Crear un ritual de buenas noches", description: "Algo especial antes de dormir." },

{ title: "Idea #331: Día de gratitud completa", description: "Agradecer por todo lo que comparten." },
{ title: "Idea #332: Armar un proyecto artístico juntos", description: "Dibujo, música, escritura, lo que quieran." },
{ title: "Idea #333: Escribir una carta sin palabras", description: "Usar solo dibujos o símbolos." },
{ title: "Idea #334: Salida de aventura urbana", description: "Explorar la ciudad como turistas." },
{ title: "Idea #335: Crear una playlist para celebrar", description: "Canciones para festejar juntos." },
{ title: "Idea #336: Hacer una lista de momentos que quieren revivir", description: "Recuerdos que quieren repetir." },
{ title: "Idea #337: Noche de charlas eternas", description: "Hablar hasta quedarse dormidos." },
{ title: "Idea #338: Escribir una carta de promesas futuras", description: "Compromisos para el mañana." },
{ title: "Idea #339: Armar una lista de cosas que los hacen fuertes", description: "Por qué funcionan juntos." },
{ title: "Idea #340: Crear una tradición anual especial", description: "Algo que hagan todos los años." },

{ title: "Idea #341: Hacer una caminata al amanecer", description: "Empezar el día viendo salir el sol." },
{ title: "Idea #342: Escribir una carta al corazón", description: "Expresar sentimientos profundos." },
{ title: "Idea #343: Crear una playlist de noches tranquilas", description: "Música suave para relajarse." },
{ title: "Idea #344: Noche de cuentos bajo la luz tenue", description: "Contarse historias en calma." },
{ title: "Idea #345: Armar una lista de sueños para la próxima década", description: "Pensar a largo plazo juntos." },
{ title: "Idea #346: Salida a un lugar desconocido", description: "Ir a un sitio donde nunca fueron." },
{ title: "Idea #347: Escribir una carta de agradecimiento a la relación", description: "Valorar todo lo que construyeron." },
{ title: "Idea #348: Crear un ritual de cierre de semana", description: "Algo que hagan cada domingo." },
{ title: "Idea #349: Hacer una lista de todo lo que superaron juntos", description: "Reconocer su crecimiento." },
{ title: "Idea #350: Crear una playlist para soñar despiertos", description: "Música para imaginar." },

{ title: "Idea #351: Día de planes imposibles", description: "Soñar sin límites juntos." },
{ title: "Idea #352: Escribir una carta a la vida", description: "Reflexionar sobre el camino recorrido." },
{ title: "Idea #353: Noche de preguntas existenciales", description: "Hablar de la vida y el universo." },
{ title: "Idea #354: Armar una lista de metas para los próximos 5 años", description: "Planear el futuro juntos." },
{ title: "Idea #355: Crear una tradición de cumpleaños especial", description: "Algo único para cada cumpleaños." },
{ title: "Idea #356: Salida a ver la luna", description: "Observarla en silencio." },
{ title: "Idea #357: Escribir una carta de amor al futuro", description: "Expresar esperanza y sueños." },
{ title: "Idea #358: Crear una playlist para cada recuerdo importante", description: "Asociar música con momentos." },
{ title: "Idea #359: Hacer una caminata de reflexión", description: "Pensar y charlar sobre la vida." },
{ title: "Idea #360: Crear un ritual de inicio de año", description: "Algo simbólico para empezar cada año." },

{ title: "Idea #361: Día de balance de la relación", description: "Evaluar cómo están y qué mejorar." },
{ title: "Idea #362: Escribir una carta a su yo del futuro juntos", description: "Hablarle a lo que serán." },
{ title: "Idea #363: Crear una tradición de aniversario", description: "Algo que hagan siempre en esa fecha." },
{ title: "Idea #364: Hacer una lista de todo lo que quieren vivir juntos", description: "Sueños, viajes, experiencias." },
{ title: "Idea #365: Celebrar su historia", description: "Recordar todo lo vivido y festejarlo con algo especial." },

];

let completed = JSON.parse(localStorage.getItem("completed")) || [];

const list = document.getElementById("list");
const doneSpan = document.getElementById("done");
const modal = document.getElementById("modal");
const modalTitle = document.getElementById("modalTitle");
const modalDesc = document.getElementById("modalDesc");

function toggleComplete(i){
  if(completed.includes(i)){
    completed = completed.filter(x => x !== i);
  } else {
    completed.push(i);
  }
  localStorage.setItem("completed", JSON.stringify(completed));
  render();
}

function openModal(i){
  modalTitle.innerText = ideas[i].title;
  modalDesc.innerText = ideas[i].description;
  modal.style.display = "flex";
}

function closeModal(){
  modal.style.display = "none";
}

function render(){
  list.innerHTML = "";
  ideas.forEach((idea,i)=>{
    const item = document.createElement("div");
    item.className = "idea";
    if(completed.includes(i)) item.classList.add("done");

    item.innerHTML = `
      <span>${idea.title}</span>
      <div class="buttons">
        <button onclick="openModal(${i})">Ver más</button>
        <button onclick="toggleComplete(${i})">✔</button>
      </div>
    `;
    list.appendChild(item);
  });

  doneSpan.innerText = completed.length;
}

document.getElementById("markAll").onclick = () => {
  completed = ideas.map((_,i)=>i);
  localStorage.setItem("completed", JSON.stringify(completed));
  render();
};

document.getElementById("unmarkAll").onclick = () => {
  completed = [];
  localStorage.setItem("completed", JSON.stringify(completed));
  render();
};

render();
